name=GrayKazu
version=1.4.0
author=GRAY KAZU
maintainer=GRAY KAZU
sentence=Icon library for KazuOS.
paragraph=This library contains all system icons and assets used in KazuOS.
category=Display
url=https://graykazu-icon-ccp.tkhoi0821.workers.dev
architectures=*
includes=GrayKazu.h